//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.ContinuationBook = new HashSet<ContinuationBook>();
            this.ContinuationBook1 = new HashSet<ContinuationBook>();
            this.DecommissionedBooks = new HashSet<DecommissionedBooks>();
            this.PendingBooks = new HashSet<PendingBooks>();
            this.Sales = new HashSet<Sales>();
            this.Stocks = new HashSet<Stocks>();
        }
    
        public int Id { get; set; }
        public string NameOfBook { get; set; }
        public decimal Price { get; set; }
        public int AmountPages { get; set; }
        public int IdTheme { get; set; }
        public int IdAuthor { get; set; }
        public int IdPublishingHouses { get; set; }
        public System.DateTime DateOfPublish { get; set; }
        public int DravingOfBook { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual PublishingHouses PublishingHouses { get; set; }
        public virtual Themes Themes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContinuationBook> ContinuationBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContinuationBook> ContinuationBook1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecommissionedBooks> DecommissionedBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingBooks> PendingBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stocks> Stocks { get; set; }
    }
}
