//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContinuationBook
    {
        public int Id { get; set; }
        public int IdBook { get; set; }
        public int IdBook2 { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Books Books1 { get; set; }
    }
}
