//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<ContinuationBook> ContinuationBook { get; set; }
        public virtual DbSet<DecommissionedBooks> DecommissionedBooks { get; set; }
        public virtual DbSet<Info> Info { get; set; }
        public virtual DbSet<PendingBooks> PendingBooks { get; set; }
        public virtual DbSet<PublishingHouses> PublishingHouses { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
    }
}
